### ISSUE TITLE
User Search by alias and first name disabled

### ISSUE THREAD

**Issue by julian-molina** [AdvancedAlgos/UsersModule#30]
The form doesn't allow giving focus to the Alias or First Name Field. Middle Name and Last Name work well.

**Comment by Luis-Fernando-Molina** [comment]
@julian-molina check this again https://platform-dev.advancedalgos.net/users/search because I could not reproduce it.

**Comment by Luis-Fernando-Molina** [comment]
no asnwer / not reproducable
